# Neden NumPy?

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]

In [3]:
ab = []                        

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [6]:
a * b

array([ 2,  6, 12, 20])

# NumPy Array'i Oluşturmak

In [8]:
import numpy as np

In [9]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:
a = np.array([1,2,3,4,5])

In [11]:
type(a)

numpy.ndarray

In [12]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [13]:
#sifirdan array olusturma 

In [14]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [17]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [18]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.random.normal(10, 4, (3,4))

array([[ 6.73534057,  0.7818847 , 11.66570744, 11.23579546],
       [15.71008799, 10.86485033,  7.67225834,  4.94612539],
       [ 9.14250443,  4.28197816, 12.29290754,  8.73860431]])

In [20]:
np.random.randint(0,10, (3,3))

array([[0, 2, 2],
       [0, 9, 2],
       [3, 1, 1]])

# Özellikleri

* **ndim**: _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [23]:
import numpy as np

In [24]:
np.random.randint(10, size = 10)

array([3, 2, 2, 7, 7, 6, 2, 3, 6, 0])

In [25]:
a = np.random.randint(10, size = 10)

In [26]:
a.ndim

1

In [27]:
a.shape

(10,)

In [28]:
a.size

10

In [29]:
a.dtype

dtype('int32')

In [30]:
b = np.random.randint(10, size = (3,5))

In [31]:
b

array([[9, 7, 5, 4, 1],
       [5, 1, 5, 3, 6],
       [2, 7, 0, 5, 5]])

In [32]:
b.ndim

2

In [33]:
b.shape

(3, 5)

In [34]:
b.size

15

In [35]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme (Reshaping)

In [37]:
import numpy as np

In [38]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a = np.arange(1,10)

In [41]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a.ndim

1

In [43]:
b = a.reshape((1,9))

In [44]:
b.ndim

2

# Array Birlestirme (Concatenation)

In [46]:
import numpy as np

In [47]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [48]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [49]:
z = np.array([7,8,9])

In [50]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
#iki boyut

In [52]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [53]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [54]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [56]:
import numpy as np

In [57]:
x = np.array([1,2,3,99,99,3,2,1])

In [58]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [59]:
a,b,c = np.split(x, [3,5])

In [60]:
a

array([1, 2, 3])

In [61]:
b

array([99, 99])

In [62]:
c

array([3, 2, 1])

In [63]:
#iki boyutlu ayırma

In [64]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [66]:
ust, alt = np.vsplit(m, [2])

In [67]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [68]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [71]:
sag, sol = np.hsplit(m, [2])

In [72]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [73]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [75]:
import numpy as np

In [76]:
v = np.array([2,1,4,3,5])

In [77]:
v

array([2, 1, 4, 3, 5])

In [78]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [79]:
v

array([2, 1, 4, 3, 5])

In [80]:
v.sort()

In [81]:
v

array([1, 2, 3, 4, 5])

In [82]:
#iki boyutlu array siralama

In [83]:
m = np.random.normal(20,5, (3,3))

In [84]:
m

array([[18.70956732, 16.34029423, 16.69080222],
       [15.60329383, 16.08621675, 18.53856427],
       [22.38011806, 12.78529158, 21.62461327]])

In [85]:
np.sort(m, axis = 1)

array([[16.34029423, 16.69080222, 18.70956732],
       [15.60329383, 16.08621675, 18.53856427],
       [12.78529158, 21.62461327, 22.38011806]])

In [86]:
np.sort(m, axis = 0)

array([[15.60329383, 12.78529158, 16.69080222],
       [18.70956732, 16.08621675, 18.53856427],
       [22.38011806, 16.34029423, 21.62461327]])

# Index ile Elemanlara Erişmek

In [88]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([6, 8, 9, 0, 6, 6, 2, 2, 3, 5])

In [89]:
a[0]

6

In [90]:
a[-1]

5

In [91]:
a[0] = 100

In [92]:
a

array([100,   8,   9,   0,   6,   6,   2,   2,   3,   5])

In [93]:
m = np.random.randint(10, size = (3,5))
m

array([[3, 5, 4, 4, 7],
       [4, 8, 5, 4, 2],
       [6, 6, 5, 4, 8]])

In [94]:
m[0,0]

3

In [95]:
m[1,1]

8

In [96]:
m[1, 4]

2

In [97]:
m[1, 4] = 99

In [98]:
m

array([[ 3,  5,  4,  4,  7],
       [ 4,  8,  5,  4, 99],
       [ 6,  6,  5,  4,  8]])

In [99]:
m[1,4] = 2.2

In [100]:
m

array([[3, 5, 4, 4, 7],
       [4, 8, 5, 4, 2],
       [6, 6, 5, 4, 8]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [102]:
import numpy as np

In [103]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [104]:
a[0:3]

array([20, 21, 22])

In [105]:
a[:3]

array([20, 21, 22])

In [106]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [107]:
a[1::2]

array([21, 23, 25, 27, 29])

In [108]:
a[0::2]

array([20, 22, 24, 26, 28])

In [109]:
a[2::2]

array([22, 24, 26, 28])

In [110]:
a[0::3]

array([20, 23, 26, 29])

In [111]:
#iki boyutlu slice islemleri

In [112]:
m = np.random.randint(10, size = (5,5))

In [113]:
m

array([[2, 8, 7, 3, 9],
       [3, 4, 8, 8, 9],
       [3, 3, 4, 0, 8],
       [5, 2, 5, 7, 3],
       [4, 7, 1, 6, 8]])

In [114]:
m[:,0]

array([2, 3, 3, 5, 4])

In [115]:
m[:,1]

array([8, 4, 3, 2, 7])

In [116]:
m[:,4]

array([9, 9, 8, 3, 8])

In [117]:
m

array([[2, 8, 7, 3, 9],
       [3, 4, 8, 8, 9],
       [3, 3, 4, 0, 8],
       [5, 2, 5, 7, 3],
       [4, 7, 1, 6, 8]])

In [118]:
m[0,:]

array([2, 8, 7, 3, 9])

In [119]:
m[0]

array([2, 8, 7, 3, 9])

In [120]:
m[1,:]

array([3, 4, 8, 8, 9])

In [121]:
m[0:2, 0:3]

array([[2, 8, 7],
       [3, 4, 8]])

In [122]:
m[:,0:2]

array([[2, 8],
       [3, 4],
       [3, 3],
       [5, 2],
       [4, 7]])

In [123]:
m

array([[2, 8, 7, 3, 9],
       [3, 4, 8, 8, 9],
       [3, 3, 4, 0, 8],
       [5, 2, 5, 7, 3],
       [4, 7, 1, 6, 8]])

In [124]:
m[1:3, 0:2]

array([[3, 4],
       [3, 3]])

# Alt Küme Üzerinde İşlem Yapmak

In [126]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[6, 6, 9, 1, 3],
       [8, 2, 1, 6, 6],
       [7, 8, 5, 0, 4],
       [2, 4, 8, 2, 0],
       [7, 5, 0, 1, 7]])

In [127]:
alt_a = a[0:3, 0:2]
alt_a

array([[6, 6],
       [8, 2],
       [7, 8]])

In [128]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [129]:
alt_a

array([[99999,     6],
       [    8,   888],
       [    7,     8]])

In [130]:
a

array([[99999,     6,     9,     1,     3],
       [    8,   888,     1,     6,     6],
       [    7,     8,     5,     0,     4],
       [    2,     4,     8,     2,     0],
       [    7,     5,     0,     1,     7]])

In [131]:
m = np.random.randint(10, size = (5, 5))
m

array([[1, 7, 7, 0, 6],
       [5, 9, 6, 4, 8],
       [3, 6, 8, 9, 1],
       [0, 2, 1, 8, 2],
       [2, 4, 0, 2, 3]])

In [132]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[1, 7],
       [5, 9],
       [3, 6]])

In [133]:
alt_b[0,0] = 9999

In [134]:
alt_b

array([[9999,    7],
       [   5,    9],
       [   3,    6]])

In [135]:
m

array([[1, 7, 7, 0, 6],
       [5, 9, 6, 4, 8],
       [3, 6, 8, 9, 1],
       [0, 2, 1, 8, 2],
       [2, 4, 0, 2, 3]])

# Fancy Index ile Elemanlara Erişmek

In [137]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [138]:
v[1]

3

In [139]:
v[3]

9

In [140]:
v[5]

15

In [141]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [142]:
al_getir = [1,3,5]

In [143]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [144]:
v[al_getir]

array([ 3,  9, 15])

In [145]:
#iki boyutta fancy

In [146]:
m = np.arange(9).reshape((3,3))

In [147]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [148]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [149]:
m[satir, sutun]

array([1, 5])

In [150]:
#basit index ile fancy index

In [151]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [152]:
m[0, [1,2]]

array([1, 2])

In [153]:
#slice ile fancy

In [154]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [156]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [157]:
v < 3

array([ True,  True, False, False, False])

In [158]:
v[v < 3]

array([1, 2])

In [159]:
v[v > 3]

array([4, 5])

In [160]:
v[v >= 3]

array([3, 4, 5])

In [161]:
v[v <= 3]

array([1, 2, 3])

In [162]:
v[v == 3]

array([3])

In [163]:
v[v != 3]

array([1, 2, 4, 5])

In [164]:
v

array([1, 2, 3, 4, 5])

In [165]:
v * 2

array([ 2,  4,  6,  8, 10])

In [166]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [167]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [168]:
v**2

array([ 1,  4,  9, 16, 25])

# Matematiksel İşlemler

In [170]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [171]:
v - 1

array([0, 1, 2, 3, 4])

In [172]:
v * 5

array([ 5, 10, 15, 20, 25])

In [173]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [174]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [175]:
#ufunc

In [176]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [177]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [178]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [179]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [180]:
v**2

array([ 1,  4,  9, 16, 25])

In [181]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [182]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [183]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [184]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [185]:
np.absolute(np.array([-3]))

array([3])

In [186]:
np.sin(360)

0.9589157234143065

In [187]:
np.cos(180)

-0.5984600690578581

In [188]:
v = np.array([1,2,3])

In [189]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [190]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [191]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [192]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\lerha\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\lerha\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [193]:
#cheatsheet

# İstatistiksel Hesaplamalar

In [195]:
v

array([1, 2, 3])

In [196]:
np.mean(v)

2.0

In [197]:
v.sum()

6

In [198]:
v.min()

1

* np.mean(arr,axis=0) | Returns mean along specific axis

* arr.sum() | Returns sum of arr

* arr.min() | Returns minimum value of arr

* arr.max(axis=0) | Returns maximum value of specific axis

* np.var(arr) | Returns the variance of array

* np.std(arr,axis=1) | Returns the standard deviation of specific axis

* arr.corrcoef() | Returns correlation coefficient of array

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [201]:
import numpy as np

**5 * x0 + x1 = 12  
x0 + 3 * x1 = 10**

In [203]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [204]:
a

array([[5, 1],
       [1, 3]])

In [205]:
b

array([12, 10])

In [206]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])

# BOLUM SONU DEGERLENDIRMESI

# Pandas Serisi Oluşturmak

In [209]:
import pandas as pd 

In [210]:
pd.Series([10,88,3,4,5])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [211]:
seri = pd.Series([10,88,3,4,5])

In [212]:
type(seri)

pandas.core.series.Series

In [213]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [214]:
seri.dtype

dtype('int64')

In [215]:
seri.size

5

In [216]:
seri.ndim

1

In [217]:
seri.values

array([10, 88,  3,  4,  5], dtype=int64)

In [218]:
seri.head(3)

0    10
1    88
2     3
dtype: int64

In [219]:
seri.tail(3)

2    3
3    4
4    5
dtype: int64

In [220]:
#index isimlendirmesi

In [221]:
pd.Series([99,22,332,94,5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [222]:
pd.Series([99,22,332,94,5], index = [1,3,5,7,9])

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [223]:
pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [224]:
seri = pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

In [225]:
seri["a"]

99

In [226]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

In [227]:
#sozluk uzerinden liste olusturmak

In [228]:
sozluk = {"reg":10, "log":11, "cart": 12}

In [229]:
seri = pd.Series(sozluk)

In [230]:
seri

reg     10
log     11
cart    12
dtype: int64

In [231]:
#iki seriyi birlestirerek seri olusturma

In [232]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

# Eleman İşlemleri

In [234]:
import numpy as np
a = np.array([1,2,33,444,75])
seri = pd.Series(a)
seri

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [235]:
seri[0]

1

In [236]:
seri[0:3]

0     1
1     2
2    33
dtype: int32

In [237]:
seri = pd.Series([121,200,150,99], 
                 index = ["reg","loj","cart","rf"])

In [238]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [239]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [240]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [241]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [242]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [243]:
#eleman sorgulama

In [244]:
"reg" in seri

True

In [245]:
"a" in seri

False

In [246]:
seri["reg"]

121

In [247]:
#fancy eleman

In [248]:
seri[["rf", "reg"]]

rf      99
reg    121
dtype: int64

In [249]:
seri["reg"] = 130

In [250]:
seri["reg"]

130

In [251]:
seri["reg":"loj"]

reg    130
loj    200
dtype: int64

# Pandas DataFrame Oluşturma

In [253]:
import pandas as pd

In [254]:
l = [1,2,39,67,90]

In [255]:
l

[1, 2, 39, 67, 90]

In [256]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [257]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [258]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [259]:
#df isimlendirme

In [260]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [261]:
df.columns = ("deg1","deg2","deg3")

In [262]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [263]:
type(df)

pandas.core.frame.DataFrame

In [264]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [265]:
df.shape

(3, 3)

In [266]:
df.ndim

2

In [267]:
df.size

9

In [268]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [269]:
type(df.values)

numpy.ndarray

In [270]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [271]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [272]:
a = np.array([1,2,3,4,5])

In [273]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

# Eleman İşlemleri

In [275]:
import numpy as np
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [276]:
sozluk = {"var1": s1, "var2": s2, "var3": s3}

In [277]:
sozluk

{'var1': array([6, 7, 6, 0, 5]),
 'var2': array([8, 6, 5, 6, 4]),
 'var3': array([6, 1, 6, 0, 1])}

In [278]:
df = pd.DataFrame(sozluk)

In [279]:
df

var1  var2  var3
0     6     8     6
1     7     6     1
2     6     5     6
3     0     6     0
4     5     4     1

In [280]:
df[0:1]

var1  var2  var3
0     6     8     6

In [281]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [282]:
df.index = ["a","b","c","d","e"]

In [283]:
df

var1  var2  var3
a     6     8     6
b     7     6     1
c     6     5     6
d     0     6     0
e     5     4     1

In [284]:
df["c":"e"]

var1  var2  var3
c     6     5     6
d     0     6     0
e     5     4     1

In [285]:
#silme

In [286]:
df.drop("a", axis = 0)

var1  var2  var3
b     7     6     1
c     6     5     6
d     0     6     0
e     5     4     1

In [287]:
df

var1  var2  var3
a     6     8     6
b     7     6     1
c     6     5     6
d     0     6     0
e     5     4     1

In [288]:
df.drop("a", axis = 0, inplace = True)

In [289]:
df

var1  var2  var3
b     7     6     1
c     6     5     6
d     0     6     0
e     5     4     1

In [290]:
#fancy 

In [291]:
l = ["c","e"]

In [292]:
df.drop(l, axis = 0)

var1  var2  var3
b     7     6     1
d     0     6     0

In [293]:
#degiskenler icin

In [294]:
df

var1  var2  var3
b     7     6     1
c     6     5     6
d     0     6     0
e     5     4     1

In [295]:
"var1" in df

True

In [296]:
l = ["var1","var4","var2"]

In [297]:
for i in l:
    print(i in df)

True
False
True


In [298]:
df

var1  var2  var3
b     7     6     1
c     6     5     6
d     0     6     0
e     5     4     1

In [299]:
df["var1"]

b    7
c    6
d    0
e    5
Name: var1, dtype: int32

In [300]:
df["var4"] = df["var1"] / df["var2"]

In [301]:
df

var1  var2  var3      var4
b     7     6     1  1.166667
c     6     5     6  1.200000
d     0     6     0  0.000000
e     5     4     1  1.250000

In [302]:
#degisken silmek

In [303]:
df.drop("var4", axis = 1)

var1  var2  var3
b     7     6     1
c     6     5     6
d     0     6     0
e     5     4     1

In [304]:
df

var1  var2  var3      var4
b     7     6     1  1.166667
c     6     5     6  1.200000
d     0     6     0  0.000000
e     5     4     1  1.250000

In [305]:
df.drop("var4", axis = 1, inplace = True)

In [306]:
df

var1  var2  var3
b     7     6     1
c     6     5     6
d     0     6     0
e     5     4     1

In [307]:
l = ["var1","var2"]

In [308]:
df.drop(l, axis = 1)

var3
b     1
c     6
d     0
e     1

# Gözlem ve Değişken Seçimi: loc & iloc

In [310]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    26    25    22
1     5     5     8
2    23     9    23
3     1    12     8
4     4    14    18
5    15    29    11
6    15     6    21
7    18     6    13
8    27     4    15
9     6    13    26

In [311]:
#loc: tanımlandığı şekli ile seçim yapmak için kullanılır.

In [312]:
df.loc[0:3]

var1  var2  var3
0    26    25    22
1     5     5     8
2    23     9    23
3     1    12     8

In [313]:
#iloc: alışık olduğumuz indeksleme mantığı ile seçim yapar.

In [314]:
df.iloc[0:3]

var1  var2  var3
0    26    25    22
1     5     5     8
2    23     9    23

In [315]:
df.iloc[0,0]

26

In [316]:
df

var1  var2  var3
0    26    25    22
1     5     5     8
2    23     9    23
3     1    12     8
4     4    14    18
5    15    29    11
6    15     6    21
7    18     6    13
8    27     4    15
9     6    13    26

In [317]:
df.iloc[:3,:2]

var1  var2
0    26    25
1     5     5
2    23     9

In [318]:
df.loc[0:3, "var3"]

0    22
1     8
2    23
3     8
Name: var3, dtype: int32

In [319]:
df.loc[0:3, "var3"]

0    22
1     8
2    23
3     8
Name: var3, dtype: int32

In [320]:
df.iloc[0:3]["var3"]

0    22
1     8
2    23
Name: var3, dtype: int32

# Koşullu Eleman İşlemleri

In [322]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    15     7    23
1    21    22    28
2    11     2     2
3    23    22     6
4    11    14     7
5    12     5    18
6    19     8    18
7     8    15    21
8    29     3     7
9     2     9    26

In [323]:
df["var1"]

0    15
1    21
2    11
3    23
4    11
5    12
6    19
7     8
8    29
9     2
Name: var1, dtype: int32

In [324]:
df[0:2][["var1","var2"]]

var1  var2
0    15     7
1    21    22

In [325]:
df

var1  var2  var3
0    15     7    23
1    21    22    28
2    11     2     2
3    23    22     6
4    11    14     7
5    12     5    18
6    19     8    18
7     8    15    21
8    29     3     7
9     2     9    26

In [326]:
df.var1

0    15
1    21
2    11
3    23
4    11
5    12
6    19
7     8
8    29
9     2
Name: var1, dtype: int32

In [327]:
df[df.var1 > 15]

var1  var2  var3
1    21    22    28
3    23    22     6
6    19     8    18
8    29     3     7

In [328]:
df[(df.var1 > 15) & (df.var3 < 5)]

Empty DataFrame
Columns: [var1, var2, var3]
Index: []

In [329]:
df.loc[(df.var1 > 15), ["var1","var2"]]

var1  var2
1    21    22
3    23    22
6    19     8
8    29     3

In [330]:
df[(df.var1 > 15)][["var1","var2"]]

var1  var2
1    21    22
3    23    22
6    19     8
8    29     3

# Birleştirme (Join) İşlemleri

In [332]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df1

var1  var2  var3
0     2    24    20
1    24    11    19
2    19    21    11
3    17    19    25
4    13    17    27

In [333]:
df2 = df1 + 99

In [334]:
df2

var1  var2  var3
0   101   123   119
1   123   110   118
2   118   120   110
3   116   118   124
4   112   116   126

In [335]:
pd.concat([df1,df2])

var1  var2  var3
0     2    24    20
1    24    11    19
2    19    21    11
3    17    19    25
4    13    17    27
0   101   123   119
1   123   110   118
2   118   120   110
3   116   118   124
4   112   116   126

In [336]:
?pd.concat

Signature:
pd.concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
  

In [337]:
pd.concat([df1,df2], ignore_index=True)

var1  var2  var3
0     2    24    20
1    24    11    19
2    19    21    11
3    17    19    25
4    13    17    27
5   101   123   119
6   123   110   118
7   118   120   110
8   116   118   124
9   112   116   126

In [338]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [339]:
df2.columns = ["var1","var2","deg3"]

In [340]:
df2

var1  var2  deg3
0   101   123   119
1   123   110   118
2   118   120   110
3   116   118   124
4   112   116   126

In [341]:
df1

var1  var2  var3
0     2    24    20
1    24    11    19
2    19    21    11
3    17    19    25
4    13    17    27

In [342]:
pd.concat([df1, df2])

var1  var2  var3   deg3
0     2    24  20.0    NaN
1    24    11  19.0    NaN
2    19    21  11.0    NaN
3    17    19  25.0    NaN
4    13    17  27.0    NaN
0   101   123   NaN  119.0
1   123   110   NaN  118.0
2   118   120   NaN  110.0
3   116   118   NaN  124.0
4   112   116   NaN  126.0

In [343]:
pd.concat([df1, df2], join = "inner")

var1  var2
0     2    24
1    24    11
2    19    21
3    17    19
4    13    17
0   101   123
1   123   110
2   118   120
3   116   118
4   112   116

In [344]:
pd.concat([df1, df2], ignore_index=True)

var1  var2  var3   deg3
0     2    24  20.0    NaN
1    24    11  19.0    NaN
2    19    21  11.0    NaN
3    17    19  25.0    NaN
4    13    17  27.0    NaN
5   101   123   NaN  119.0
6   123   110   NaN  118.0
7   118   120   NaN  110.0
8   116   118   NaN  124.0
9   112   116   NaN  126.0

# İleri Birleştirme İşlemleri

In [346]:
import pandas as pd

In [347]:
#birebir birlestirme

In [348]:
df1 = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'İK']})

df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [349]:
df2 = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],
                    'ilk_giris': [2010, 2009, 2014, 2019]})

df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [350]:
pd.merge(df1, df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [351]:
pd.merge(df1, df2, on = "calisanlar")

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [352]:
#coktan teke 

In [353]:
df3 = pd.merge(df1, df2)

In [354]:
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [355]:
df4 = pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'İK'],
                    'mudur': ['Caner', 'Mustafa', 'Berkcan']})

df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [356]:
pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [357]:
# çoktan çoka

In [358]:
df5 = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                              'Muhendislik', 'Muhendislik', 'İK', 'İK'],
                    'yetenekler': ['matematik', 'excel', 'kodlama', 'linux',
                               'excel', 'yonetim']})

df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [359]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [360]:
pd.merge(df1, df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           İK      excel
7      Fatma           İK    yonetim

# Toplulaştırma ve Gruplama (Aggregation & Grouping)

Basit toplulaştırma fonksiyonları:

* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [363]:
import seaborn as sns

In [364]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [365]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [366]:
df.shape

(1035, 6)

In [367]:
df.mean()

TypeError: Could not convert ['Radial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityImagingImagingImagingEclipse Timing VariationsImagingImagingImagingImagingEclipse Timing VariationsEclipse Timing VariationsEclipse Timing VariationsEclipse Timing VariationsEclipse Timing VariationsEclipse Timing VariationsEclipse Timing VariationsEclipse Timing VariationsRadial VelocityRadial VelocityImagingRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityImagingRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityImagingImagingImagingImagingImagingImagingImagingImagingRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityImagingImagingTransitTransitTransitTransitTransitTransitTransitRadial VelocityTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitAstrometryRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityImagingRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityTransitRadial VelocityRadial VelocityRadial VelocityImagingTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitRadial VelocityTransitTransitTransitTransitRadial VelocityTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitRadial VelocityTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityImagingRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityImagingRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityAstrometryRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityImagingRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityRadial VelocityImagingRadial VelocityRadial VelocityRadial VelocityImagingRadial VelocityRadial VelocityRadial VelocityImagingImagingImagingImagingTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransit Timing VariationsTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitRadial VelocityTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransit Timing VariationsTransitTransitTransitTransitTransitRadial VelocityTransitTransitTransitTransitTransitTransitTransit Timing VariationsTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitRadial VelocityTransitTransitOrbital Brightness ModulationOrbital Brightness ModulationTransitTransitTransitOrbital Brightness ModulationTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransit Timing VariationsTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitRadial VelocityTransitRadial VelocityTransitTransitTransitRadial VelocityTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitRadial VelocityTransitTransitTransitTransitTransitTransitImagingTransitMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingRadial VelocityRadial VelocityRadial VelocityRadial VelocityMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingMicrolensingTransitTransitTransitTransitTransitTransitTransitTransitImagingTransitRadial VelocityRadial VelocityPulsar TimingPulsar TimingPulsar TimingPulsar TimingPulsar TimingTransitTransitImagingImagingImagingTransitTransitTransitTransitTransitTransitImagingPulsation Timing VariationsTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitTransitImagingTransitImagingTransitTransitTransitTransitTransit'] to numeric

In [ ]:
df["mass"].mean()

In [ ]:
df["mass"].count()

In [ ]:
df["mass"].min()

In [ ]:
df["mass"].max()

In [ ]:
df["mass"].sum()

In [ ]:
df["mass"].std()

In [ ]:
df["mass"].var()

In [ ]:
df.describe().T

In [ ]:
df.dropna().describe().T

# Gruplama İşlemleri

In [ ]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'veri': [10,11,52,23,43,55]}, columns=['gruplar', 'veri'])
df

In [ ]:
df.groupby("gruplar")

In [ ]:
df.groupby("gruplar").mean()

In [ ]:
df.groupby("gruplar").sum()

In [ ]:
df = sns.load_dataset("planets")
df.head()

In [ ]:
df.groupby("method")

In [ ]:
df.groupby("method")["orbital_period"].mean()

In [ ]:
df.groupby("method")["orbital_period"].describe()

# İleri Toplulaştırma İşlemleri (Aggregate, filter, transform, apply)

In [ ]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

In [ ]:
#aggregate

In [ ]:
df.groupby("gruplar").mean()

In [ ]:
df.groupby("gruplar").aggregate([min, np.median, max])

In [ ]:
df.groupby("gruplar").aggregate({"degisken1": "min", "degisken2": "max"})

In [ ]:
#filter

In [ ]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

In [ ]:
def filter_func(x):
    return x["degisken1"].std() > 9

In [ ]:
df.groupby("gruplar").std()

In [ ]:
df.groupby("gruplar").filter(filter_func)

In [ ]:
#transform

In [ ]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

In [ ]:
df["degisken1"]*9

In [ ]:
df_a = df.iloc[:,1:3]

In [ ]:
df_a.transform(lambda x: (x-x.mean()) / x.std())

In [ ]:
#apply

In [ ]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

In [ ]:
df.apply(np.sum)

In [ ]:
df.apply(np.mean)

In [ ]:
df.groupby("gruplar").apply(np.mean)

# Pivot Tablolar

In [ ]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

In [ ]:
titanic.groupby("sex")[["survived"]].mean()

In [ ]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

In [ ]:
#pivot ile table

In [ ]:
titanic.pivot_table("survived", index = "sex", columns = "class")

In [ ]:
titanic.age.head()

In [ ]:
age = pd.cut(titanic["age"], [0, 18, 90])
age.head(10)

In [ ]:
titanic.pivot_table("survived", ["sex", age], "class")

# Dış Kaynaklı Veri Okumak

In [ ]:
import pandas as pd

In [ ]:
?pd.read_csv

In [ ]:
#csv okuma
pd.read_csv("reading_data/ornekcsv.csv", sep = ";")

In [ ]:
#txt okuma
pd.read_csv("reading_data/duz_metin.txt")

In [ ]:
#excel
pd.read_excel("reading_data/ornekx.xlsx")

In [ ]:
df = pd.read_excel("reading_data/ornekx.xlsx")

In [ ]:
type(df)

In [ ]:
df.head()

In [ ]:
df.columns = ("A","B","C")

In [ ]:
df

In [ ]:
#sıfırdan txt okuma
tips = pd.read_csv("reading_data/data.txt")

In [ ]:
tips.head()

# Bonus: Problem Çözme ve Döküman Okuma Kültürü

In [ ]:
9 / 0

# BOLUM SONU DEGERLENDIRMESI